### PR TITLE
fix the confirmation dialog

### PR DESCRIPTION
**Pull request by uKiJo**
## Description
Fixing the confirmation deletion dialog to make it conform to the design system of the application.

## How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
This is a little bit lengthy

image

**Comment by SauveJeanLuc** [comment]
It's not fixed yet @uKiJo

**Comment by SauveJeanLuc** [comment]
Replace "Yes I am sure " with Delete

**Comment by SauveJeanLuc** [comment]
Fix linting and we are good to go

image

**Comment by SauveJeanLuc** [comment]
Also check #62

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by uKiJo** [comment]
> Fix linting and we are good to go
> 
> image

i don't have those error when running the linter script...

**Pull request merged**
