### PR TITLE
feat: add a description field to the todo

### PR DESCRIPTION
**Pull request by gaber85**
## Description

This PR adds a description field, an optional field where the user can type important information about the task. 

This field will follow the same pattern and behavior as the other existing inputs.

## Related Issue

The related issue is https://github.com/SauveJeanLuc/coffee-tasks/issues/138.

## Motivation and Context

Currently there is only a title and status, but no field where the user can write a description or notes about the task. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
1. Don't you think this option will ruin the app's simplicity?
2. I can see the description is not optional at all, I can still see the input text wether I want to put it or not.

**Comment by gaber85** [comment]
@SauveJeanLuc Not at all, in fact it adds value to the users that want to add more info about the task. It still keeps the simplicity. No worries if you don't feel comfortable adding this feature. After all you are directing how this app should be! I can make tweaks if you like the idea.

The optional aspect of the field is that you don't need to add text to it if you don't want to, unlike the title, where you cannot leave it blank and is required.

**Comment by SauveJeanLuc** [comment]
Great, go on with the tweaks in a way that maintains the app's simplicity.
Like I don't have to see the description textbox, if I'm not really willing to add the description

**Comment by gaber85** [comment]
@SauveJeanLuc that sounds good, I'll make the changes and push it back up!

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
