### PR TITLE
add confirmation dialog

### PR DESCRIPTION
**Pull request by uKiJo**
## Description

Added a feature related to an open issue of adding a confirmation dialog that allows user to confirm the deletion process.
## Related Issue
Delete a task should have a confirmation dialog

## Screenshots (if appropriate):
dialog

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
@all-contributors add @uKiJo for code

**Comment by SauveJeanLuc** [comment]
@uKiJo , dialog should be responsive and centered on small devices

**Comment by uKiJo** [comment]
> @uKiJo , dialog should be responsive and centered on small devices

I think it is completely responsive, by centering, do you mean vertically?

Sans titre

**Comment by SauveJeanLuc** [comment]
> > @uKiJo , dialog should be responsive and centered on small devices
> 
> I think it is completely responsive, by centering, do you mean vertically?
> 
> Sans titre

Yup

**Pull request closed without merging**
