### PR TITLE
working on the add task button so it shows the popup and adding functionality to the cancel button 

### PR DESCRIPTION
**Pull request by ChahineBendjeddou**
## How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by ChahineBendjeddou — COMMENTED** [review]
factoring the popup code a bit

**Comment by SauveJeanLuc** [comment]
@ChahineBendjeddou You did a great job 🎉
Do you mind giving a little bit descriptive information in your PR request.
Plus link it with all issues that it's solving ? So that they are closed when I merge.

**Comment by ChahineBendjeddou** [comment]
@SauveJeanLuc  okey i'll work on it

**Comment by ChahineBendjeddou** [comment]
@SauveJeanLuc how can i link the issues if you dont mind me asking ?

**Comment by SauveJeanLuc** [comment]
@ChahineBendjeddou  Rebase

**Comment by ChahineBendjeddou** [comment]
@SauveJeanLuc  done

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc done

The conflicts are still there.

**Pull request closed without merging**
