### PR TITLE
Added responsiveness to the add task button and select button

### PR DESCRIPTION
**Pull request by Prakhar-Goyal-3014**
Issue #61 solved
Screenshot 2022-10-06 at 4 54 18 PM

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
image

**Comment by Prakhar-Goyal-3014** [comment]
@SauveJeanLuc Sorry. I will try to fix it🙂

**Comment by Prakhar-Goyal-3014** [comment]
@SauveJeanLuc you can check now I have tried to adjust the responsiveness for all the other devices.
But for galaxy fold I was unable to do it🙁 because for that I have to adjust it in column. In side by side flex it will look very small.

**Comment by Prakhar-Goyal-3014** [comment]
@SauveJeanLuc finally did it you can check. Just commited the complete responsiveness.

**Comment by SauveJeanLuc** [comment]
LGTM

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by SauveJeanLuc** [comment]
@all-contributors add @Prakhar-Goyal-3014 for code

**Pull request merged**
