### PR TITLE
eslint setup with some code fixes

### LINKED ISSUE #16: Add ES-Lint Configuration To The  Project
Projects need ESLint SetUp in order to make code more consistent and avoid bugs.

### PR DESCRIPTION
**Pull request by RohanKaran**
Eslint Configuration
fixes #16

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Are all commits Es-Lint configuration related
?

**Comment by RohanKaran** [comment]
@SauveJeanLuc yes, all of the commits are eslint related, some are minor changes due to errors by Eslint

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc yes, all of the commits are eslint related, some are minor changes are to fix errors pointed by Eslint

I can see some UI changes from the preview.
Did you notice ?

image

**Comment by RohanKaran** [comment]
@SauveJeanLuc fixed that unexpected padding change in PopUp.jsx. Can you check again?

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by SauveJeanLuc** [comment]
You can consider resolving all conflicts before I merge

**Comment by RohanKaran** [comment]
@SauveJeanLuc resolved all merge conflicts

**Pull request merged**
