### PR TITLE
Added filter and default value

### LINKED ISSUE #88: There is no default value for status
# Prerequisites

- [x] This is a bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
image
I got this error when I tried to add a task,
When I added the task without specifying the status  
I thought incomplete would be a default value, it returned an error

**To Reproduce** \
1. Go to [Homepage](https://coffeetasks.netlify.app/)
2. Click on `Add Task`
3. add a title
4. click on `Add task`
5. See the error 

**Expected behavior** \
The status should have a default value or add an option saying choose status so users we will understand they have to select it manually

**Current behavior** \
We need to select the status manually

**Possible solutions**\

Add a default value in react-select

I would like to work on this issue

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 105.0.1

### PR DESCRIPTION
**Pull request by beelchester**
## Description
- Added filter so that tasks having the selected status will only be shown
- Added 'All' option to select button (which is the default option) to show all the tasks irrespective of their status
- Added default status for adding a new task as 'incomplete', also made changes to error message text as now only tasks' name was required from the user

## How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Can you give a more descriptive PR description

**Comment by SauveJeanLuc** [comment]
Can you maintain the size of the status select?

image

**Comment by sahilyeole** [comment]
> Can you maintain the size of the status select?
> 
> image

Yup, I had to add width to it to prevent this
Screenshot from 2022-10-09 21-12-40
So now I've added width prop with 170px only for the nav's select button

**Comment by SauveJeanLuc** [comment]
Select is a little bit longer.

image

It should at first match size approximately with add task

**Comment by sahilyeole** [comment]
> Select is a little bit longer.
> 
> image
> 
> It should at first match size approximately with add task

Fixed it

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
