### PR TITLE
Updated Figma Design

### PR DESCRIPTION
**Pull request by pobrebobby**
## Description

Updated the Figma prototype CRUD

https://www.figma.com/file/LBOp5Er4txjR8nDpwI40Rr/Coffee-Tasks-(V2)?node-id=362%3A188

Changed the words "todo" to "task"
Fixed the contrast ratio with the text color to make it comply with AAA WCAG
Created new overlay to input new task
Moved 'add' button to right side of overlay to make it easier to add quickly.
Edited the Change status overlay to include a drop down with options "done" or "to-do"
Added a button that indicates if the task is either "done" or "to-do"
Add "3 dots" for users to edit or delete the task

## Related Issue
#19 

## Motivation and Context
 
Web Content Accessibility Guidelines (WCAG) international standard
My first hackathon is my motivation.😀

## How Has This Been Tested?
I hope I didn't break anything.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots (if appropriate):
https://www.figma.com/file/LBOp5Er4txjR8nDpwI40Rr/Coffee-Tasks-(V2)?node-id=316%3A49

Coffee Tasks v2

Screen Shot 2022-10-06 at 10 51 42 AM

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Please include link to figma in your description, so others can give feedback as well.

**Comment by SauveJeanLuc** [comment]
I think we should keep the usual way we used for closing the pop-up, It's more appealing to the user.

❌
image

✅
image

**Comment by SauveJeanLuc** [comment]
Are all To-Dos going to have these emojis?
Would you explain further why we are going to have those emojis right before the To-Dos' title ?
image

**Comment by SauveJeanLuc** [comment]
I think, No To-Dos keeps it simpler for the user to read.

image

**Comment by SauveJeanLuc** [comment]
The Icons at the start should be of the same height

image

**Comment by SauveJeanLuc** [comment]
Can you explain the role of these 2 icons ?

**Comment by SauveJeanLuc** [comment]
These 2 options are so crucial for the user not to click twice to access them, you can replace them with icons
image

**Comment by SauveJeanLuc** [comment]
Update Status should not be a form, a simple checkbox can do the work.

image

I'd suggest you place the checkbox where you placed the gift emoji

**Comment by pobrebobby** [comment]
Here is the Figma file
https://www.figma.com/file/LBOp5Er4txjR8nDpwI40Rr/Coffee-Tasks-(V2)?node-id=316%3A49

**Comment by pobrebobby** [comment]
> I think, No To-Dos keeps it simpler for the user to read.
> 
> image

I think it is important to encourage the user to add a task to get started. 

"Empty states can be confusing to users, especially if there’s no indication of what they’re supposed to do to fill those screens. Use this opportunity to guide users and help them complete a task, such as setting up their first project." 
Uxcel - Nudge users to fill empty state 

"Take advantage of empty states in your product whenever you can. As soon as you see, if there’s no data on a specific page or no real task/job.These empty states are a great way to natively push for user action." https://medium.com/agileinsider/customer-onboarding-f15f9a70f834

**Comment by pobrebobby** [comment]
> Are all To-Dos going to have these emojis?
> Would you explain further why we are going to have those emojis right before the To-Dos' title ?
> image

Great question! 
I think emojis make the design more friendly and fun. I was not sure of the target user. 

I think we can drop the emojis now and just focus on the MVP, maybe in the future we can update the app with them.

**Comment by pobrebobby** [comment]
> Can you explain the role of these 2 icons ?
> 
> image

I have no idea. I just copied the original Figma file. I thought you wanted them there.

**Comment by pobrebobby** [comment]
> I think we should keep the usual way we used for closing the pop-up, It's more appealing to the user.
> 
> ❌ image
> 
> ✅ image


Done 
Added label for better usability and accessibility - screen reader
Title overlay

**Comment by pobrebobby** [comment]
> These 2 options are so crucial for the user not to click twice to access them, you can replace them with icons
> image

Done - added icons and labels
V 4 1 New task screen

**Comment by pobrebobby** [comment]
> Update Status should not be a form, a simple checkbox can do the work.
> 
> image
> 
> I'd suggest you place the checkbox where you placed the gift emoji

Done- added a radio button with a checkmark
Task 1 Checkmark

**Comment by SauveJeanLuc** [comment]
@pobrebobby , Well done but I can't see the updates on Figma.

**Comment by pobrebobby** [comment]
> @pobrebobby , Well done but I can't see the updates on Figma.

https://www.figma.com/file/LBOp5Er4txjR8nDpwI40Rr/Coffee-Tasks-(V2)?node-id=362%3A188

It should be on page Version 4.

**Comment by SauveJeanLuc** [comment]
Do you mind including in the design, what's going to happen if the user puts in a long text ?

**Comment by pobrebobby** [comment]
> Do you mind including in the design, what's going to happen if the user puts in a long text ?

Great point.
I updated the figma file with longer text expanding the text box.
Screen Shot 2022-10-08 at 9 51 32 PM

**Comment by SauveJeanLuc** [comment]
I think the icons would better be centered vertically as well.
image

**Comment by SauveJeanLuc** [comment]
The words Edit and Delete Should be Omitted, I think that will be better.

image

**Comment by pobrebobby** [comment]
> The words Edit and Delete Should be Omitted, I think that will be better.
> 
> image

I strongly believe it is better to have labels for icons because it helps the users understand quickly what the icon means.

"A user’s understanding of an icon is based on previous experience. Due to the absence of a standard usage for most icons, text labels are necessary to communicate the meaning and reduce ambiguity." Nielsen Norman Group
https://www.nngroup.com/articles/icon-usability/

"The combination of icons and a corresponding label helps everyone: people with mental impairments, the elderly who aren’t 'internet natives', and even your good self." 
https://a11y-101.com/design/icons

**Comment by Rinshin-Jalal** [comment]
> The words Edit and Delete Should be Omitted, I think that will be better.
> 
> image

I think the same 
and 
It would be better to use some other icons for editing and deleting 
because now without the text it doesn't look like a delete and edit button

**Comment by pobrebobby** [comment]
> I think the icons would better be centered vertically as well.
> image

Updated alignment to center on Figma file.
Screen Shot 2022-10-09 at 12 11 25 PM

**Comment by pobrebobby** [comment]
> > The words Edit and Delete Should be Omitted, I think that will be better.
> > image
> 
> I think the same and It would be better to use some other icons for editing and deleting because now without the text it doesn't look like a delete and edit button

Hi, Rinshin. Could you provide some icons for edit and delete that you believe would work without labels. Thanks.

**Comment by SandeshGC** [comment]
I suggest using any of these two icons for removing the tasks:
image
image

The edit icon is already self definitive.

I don't think any of them need any labels because the use of hover effects (adding tooltip or changing colors) will help enhance their view and use.

**Comment by pobrebobby** [comment]
Here's an update with no labels. Remember that with mobile there is no hover state.
Screen Shot 2022-10-09 at 2 33 52 PM

**Comment by SauveJeanLuc** [comment]
Great @pobrebobby .
All things done.

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by SauveJeanLuc** [comment]
@pobrebobby Would you take over #10 as well ?

**Comment by SauveJeanLuc** [comment]
@all-contributors add @pobrebobby for design

**Comment by SauveJeanLuc** [comment]
@pobrebobby ask me edit access on original Figma file, so you can add there all final touches

**Comment by SandeshGC** [comment]
I would like to suggest using a rounded rectangular checkbox instead of circular, because no items in the site are circular, everything is rectangular with rounded borders.

**Comment by pobrebobby** [comment]
> I would like to suggest using a rounded rectangular checkbox instead of circular, because no items in the site are circular, everything is rectangular with rounded borders.
> 
> Also, the checkbox size is a bit big right now.

@SandeshGC I just updated the Figma file with your suggestions. Let me know if it looks ok.
Screen Shot 2022-10-09 at 3 49 14 PM

**Comment by SandeshGC** [comment]
It looks perfect! @SauveJeanLuc

**Comment by Rinshin-Jalal** [comment]
> Screen Shot 2022-10-09 at 3 49 14 PM
> 

This looks perfect 💫

**Pull request merged**
