### PR TITLE
added/updated UI for mobile version in figma

### PR DESCRIPTION
**Pull request by hertafui**
## Description
Created/updated UI mobile version 
https://www.figma.com/file/LBOp5Er4txjR8nDpwI40Rr/Coffee-Tasks-(V2)?node-id=409%3A260

- Make prototype refer to user flow
- Added 'has been deleted state' page
- Added trash icon/illustration asset for the 'has been deleted state' page
- Added 'task added successfully' page
- Added check/success illustration asset for the 'task added successfully page

## Related Issue
#10 

## Screenshots (if appropriate):
Screenshot at 2022-10-10 19-27-11

### CODE REVIEW

**Comment by pobrebobby** [comment]
Also, I think we can get rid of the word "Title" on the overlay, right?

Add task
Add task without title

**Comment by hertafui** [comment]
Yes, the "Title" is not too necessary though (it already covered by "New Task").  About the filter I think the stroke color that makes the button kinda old-ish. It would be better if change it into grey/neutral instead of red or primary color. 

And also the overlay, I think the backround would be look more modern-ish if use the neutral color instead of fade red.

Actually, I just followed the web version before, I was afraid to make a lot changes, so I just did a little changes for mobile version.
What do you think?  [pobrebobby](https://github.com/pobrebobby)

**Comment by pobrebobby** [comment]
> Yes, the "Title" is not too necessary though (it already covered by "New Task"). About the filter I think the stroke color that makes the button kinda old-ish. It would be better if change it into grey/neutral instead of red or primary color.
> 
> And also the overlay, I think the backround would be look more modern-ish if use the neutral color instead of fade red.
> 
> Actually, I just followed the web version before, I was afraid to make a lot changes, so I just did a little changes for mobile version. What do you think? [pobrebobby](https://github.com/pobrebobby)

LOL, I made a lot of changes at first and it was denied. This group is pretty cool, so you should make different changes and then ask them what they think. They might like it. 

By the way, I'm a newbie and I was wondering about the size of your buttons. I was taught that iOS has to be minimum 44px and Android has to 48px. What do you think?

**Comment by SauveJeanLuc** [comment]
Great job.

I think this has to be applied to task completion instead (as a congratulations message).
image

I can't see any reason to have it on task creation.

Though, This will have to be implemented on web as well.

**Comment by hertafui** [comment]
> > Yes, the "Title" is not too necessary though (it already covered by "New Task"). About the filter I think the stroke color that makes the button kinda old-ish. It would be better if change it into grey/neutral instead of red or primary color.
> > And also the overlay, I think the backround would be look more modern-ish if use the neutral color instead of fade red.
> > Actually, I just followed the web version before, I was afraid to make a lot changes, so I just did a little changes for mobile version. What do you think? [pobrebobby](https://github.com/pobrebobby)
> 
> LOL, I made a lot of changes at first and it was denied. This group is pretty cool, so you should make different changes and then ask them what they think. They might like it.
> 
> By the way, I'm a newbie and I was wondering about the size of your buttons. I was taught that iOS has to be minimum 44px and Android has to 48px. What do you think?

I usually use 42px for the minimum buttons size, I've heard about the minimum size for iOS and Android before but my bad I didn't check it first lol. Thanks for the information anyway @pobrebobby .

**Comment by SauveJeanLuc** [comment]
Why do you think these buttons should be positioned otherwise on mobile version ?

image

image

**Comment by hertafui** [comment]
> Why do you think these buttons should be positioned otherwise on mobile version ?
> 
> image
> 
> image

I thought it would be more better if the primary button dropped in the right section, cause mostly mobile users using their right finger to reach and click the button.
I think it can be applied to the web version as well, since I usually see the primary button always dropped in the right (like this comment button). What do you think?

**Comment by SauveJeanLuc** [comment]
> Why do you think these buttons should be positioned otherwise on mobile version ?
> 
> image
> 
> image

Take a look at this one @hertafui

**Comment by SauveJeanLuc** [comment]
> Great job.
> 
> I think this has to be applied to task completion instead (as a congratulations message). image
> 
> I can't see any reason to have it on task creation.
> 
> Though, This will have to be implemented on web as well.

Take a look at this one @hertafui

**Comment by hertafui** [comment]
> > Great job.
> > I think this has to be applied to task completion instead (as a congratulations message). image
> > I can't see any reason to have it on task creation.
> > Though, This will have to be implemented on web as well.
> 
> Take a look at this one @hertafui

Yeah, I just realized that, I think you were right, it will be suitable as congratulation when finished task instead

**Comment by SauveJeanLuc** [comment]
> > > Great job.
> > > I think this has to be applied to task completion instead (as a congratulations message). image
> > > I can't see any reason to have it on task creation.
> > > Though, This will have to be implemented on web as well.
> > 
> > 
> > Take a look at this one @hertafui
> 
> Yeah, I just realized that, I think you were right, it will be suitable as congratulation when finished task instead. @SauveJeanLuc

You can make a design for that as well.
It will be included in upcoming issues for devs to work on.

**Comment by SauveJeanLuc** [comment]
@hertafui  Raise a PR to add the link to Figma in README.md

**Comment by SauveJeanLuc** [comment]
@all-contributors add @hertafui for design

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
