### PR TITLE
Make coffee task a progressive web application 

### LINKED ISSUE #75: Convert application to a Progressive Web Application
### Make the website more dynamic by implementing progressive application
In SAUVE Jean-Luc's words, To-Do List Apps are often underrated but a lot can be done by building one, from basic crud implementation to progressive web application implementation. 
I would like to make the coffee-tasks application a progressive web for the following reasons: 
- The coffee-tasks application can be accessible offline
- One-click access to the coffee-tasks application once it is saved to the Home screen.

### PR DESCRIPTION
**Pull request by t-bello7**
## Description
- Added vite-plugin-PWA to devdependencies of coffee-task application. Vite-plugin-PWA automatically creates a service worker.
- Added PWA manifest requirements which include logo assets in the required sizes and file type
- Added the install button on the homepage to render if the user has not installed the coffee-task application

## Related Issue
Closes #75 

## Motivation and Context
I am currently learning the benefits and implementation of PWAs and thought what better way to learn than getting feedback from other developers? The Coffee tasks application is one that would have a better user experience if the user can just click on the application from either their home screen or desktop screen depending on the device used to visit the website. 

## How Has This Been Tested?
To test the application in development :
- Add the code below to the variable pwaOptions in the vite.config.js file
```
devOptions: {
enabled: true,
navigateFallBack: 'index.html',
},
mode: 'development',
``` 
- Run ` yarn dev` in your terminal. The server can now be accessed from localhost in your browser.
- Open the developer tool in your browser and generate the website report using lighthouse.
Screenshot from 2022-10-09 22-06-03
- The PWA check is all passed

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Good Job.
But I'm seeing the install button, only when I've already installed the app.
image

**Comment by SauveJeanLuc** [comment]
Also, you'll have to pull from master, to have the latest changes involved.

**Comment by t-bello7** [comment]
Alright.

**Comment by SauveJeanLuc** [comment]
Great job @t-bello7 .

Aniwei, Don't you have alternative ways to prompt installation?
Like maybe a beautiful pop-up ?
This button seems to disturb the aesthetics and simplicity of the app.

image

You can use the same pop-up design, but with different content.
image

At this stage, it will contain the app logo at the Top (Well positioned).
A descriptive phrase to prompt the user to download, in the middle.
Plus a well-positioned button for downloading at the bottom.

**Comment by t-bello7** [comment]
Noted @SauveJeanLuc I would work on it.

**Comment by SauveJeanLuc** [comment]
> Noted @SauveJeanLuc I would work on it.

Actually, at this stage you can just remove the download button, resolve conflicts, and the browser will handle everything.

**Comment by SauveJeanLuc** [comment]
Can you pull all the latest changes from the master?
I think at this stage, we will be good to go, and I'll merge.

Either way, I'd like to ask. If any other change is applied to this web app, will it also apply to the PWA?

**Comment by t-bello7** [comment]
The application would remain a PWA provided the application is mobile responsive and changes made don't make breaking changes to the manifest and service worker code in the  vite.config.js 
Screenshot from 2022-10-13 23-18-47

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by SauveJeanLuc** [comment]
@all-contributors add @t-bello7 for code

**Pull request merged**
