### PR TITLE
readme updated

### LINKED ISSUE #36: Beautify README.md
- Properly Align the texts. 
- Fix Typo. 
- Improve the Image
Show your creativity.

### PR DESCRIPTION
**Pull request by divyanshraj0408**
## Description
Updated the readme with the context provided in #36 
* Updated instructions for installing and running the project in localhost
* Updated gif for the preview of application
* closes #36 
## Motivation and Context
These changes make the readme more beautiful and more read readable.

## How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Can't see app logo and title in the Gif

**Comment by divyanshraj0408** [comment]
Fixed both the issues :+1: 

> We've lost some contributors in your change.



> Can't see app logo and title in the Gif

**Comment by SauveJeanLuc** [comment]
> Fixed both the issues 👍
> 
> > We've lost some contributors in your change.
> 
> > Can't see app logo and title in the Gif

Would you mind removing the redundant contributor section ?
I'd suggest the last one to removed.

**Comment by SauveJeanLuc** [comment]
Few things remaining.

- Would you remove this right black border on the SVG
image

- Isn't there a way we can have an SVG with higher quality? The current one seems a little bit blurry.

**Comment by divyanshraj0408** [comment]
Do we want an SVG or GIF ? I think a gif can explain the project well and in a precise way, but most online gif converters have this problem of low quality.

**Comment by SauveJeanLuc** [comment]
> Do we want an SVG or GIF ? I think a gif can explain the project well and in a precise way, but most online gif converters have this problem of low quality.

GIF, 
Sorry. I was mistaken

**Comment by divyanshraj0408** [comment]
ezgif com-gif-maker
does this seem okay?

**Comment by SauveJeanLuc** [comment]
> ezgif com-gif-maker [ ezgif com-gif-maker ](https://user-images.githubusercontent.com/73312468/194117721-5dd0f3fc-98e3-4827-b964-941446f1f014.gif) [ ](https://user-images.githubusercontent.com/73312468/194117721-5dd0f3fc-98e3-4827-b964-941446f1f014.gif) does this seem okay?

Yup, we can go with it.

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
