### PR TITLE
feat(UI): delete, change status, edit tasks 

### LINKED ISSUE #85: List Tasks according to New Design
Tasks or To-Dos should be listed according to the new design.

image

### PR DESCRIPTION
**Pull request by adi-uchiha**
Closes #85 
## Description
- [x] Made the application highly responsive
- [x] User can delete tasks
- [x] User can edit tasks

## Related Issue
#85 

## How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
-  
chrome_Fi5TcfAxfC
] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Edit is creating a new task instead

**Comment by SauveJeanLuc** [comment]
The two buttons should remain.
Only that, you will replace Create Task by Edit Task.
image

**Comment by adi-uchiha** [comment]
Yup I see that there is a logical mistake done by me. It can be fixed easily. And I will add back the cancel button as well.

**Comment by adi-uchiha** [comment]
@SauveJeanLuc hey I just checked. I think it is working fine. Edit task is NOT creating new tasks. 
Tho I will add a commit to put the cancel button next to edit button. 
edit task is working fine. I checked in deployment preview => https://deploy-preview-119--coffeetasks.netlify.app/

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc hey I just checked. I think it is working fine. Edit task is NOT creating new tasks. Tho I will add a commit to put the cancel button next to edit button. edit task is working fine. I checked in deployment preview => https://deploy-preview-119--coffeetasks.netlify.app/

I mean, When I press enter.

**Comment by SauveJeanLuc** [comment]
Also, position well the Edit and Cancel Buttons as the ones for Creation are Poisitioned.

**Comment by SauveJeanLuc** [comment]
There is an unnecessary blue border background when typing in the react select.
Screenshot (44)

**Comment by adi-uchiha** [comment]
@SauveJeanLuc is it ok now ?
- [x] Edit and cancel button are positioned just like the addtask and cancel button were.
- [x] Edit task when press enter 
- [x] made code more readable by adding one extra component `src/components/Todo.jsx`
- [x] Removed the blue border in dropdown search

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc is it ok now ?
> 
> * [x]  Edit task when press enter
> * [x]  Edit and cancel button are positioned just like the addtask and cancel button were.
> * [x]  Removed the blue border in dropdown search
> * [x]  made code more readable by adding one extra component `src/components/Todo.jsx`

Blue border is still there.

**Comment by SauveJeanLuc** [comment]
These words should be updated as well.
image

**Comment by SauveJeanLuc** [comment]
Pull from master and resolve conflicts

**Comment by SauveJeanLuc** [comment]
The Blue border is still there

**Comment by adi-uchiha** [comment]
@SauveJeanLuc  unable to fix that. Moreover I tried copy pasting the code of old commits (When there was not blue border). still the bluebox appears on new code. I did not even changed the code of `<SelectButton />` component. I think we should merge this and create a new issue for this.

**Comment by SauveJeanLuc** [comment]
Great @adi-uchiha Let's have it merged.
And you can raise an issue for it.

Here's an invite to discord: https://discord.gg/GzpQyMGz

**Review by SauveJeanLuc — APPROVED** [review]

**Comment by SauveJeanLuc** [comment]
@all-contributors add @adi-uchiha for code

**Pull request merged**
