### PR TITLE
Added Tailwind Set-up to Project 

### LINKED ISSUE #21: Add Tailwind Set-up to Project
The project is currently relying on vanilla CSS.
Add we want to add some tailwind in the ride, will you help 😺?

### PR DESCRIPTION
**Pull request by Onyelaudochukwuka**
## Description
Changed all inline styles to tailwindcss

## Related Issue
Fixes #21 

## Motivation and Context
It reduces the code required in each component

## How Has This Been Tested?
I tested the changes locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
@Onyelaudochukwuka,
I think the animations are not necessary for this stage

**Comment by Onyelaudochukwuka** [comment]
Ok it take them out.
Just the pop-up animation right ?

**Comment by SauveJeanLuc** [comment]
> Ok it take them out. Just the pop-up animation right ?

Yh, you can remove one for pop-up.
And make the rest faster.

**Comment by Onyelaudochukwuka** [comment]
ok

**Comment by Onyelaudochukwuka** [comment]
Done This

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
