### PR TITLE
added 'create new task' functionality using local storage ( fixed issue #2 ) 

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
Now on clicking the add Task button, the data is stored permanently on local storage.  fixed issue #2 

Please let me know if you need any changes.
Thanks :)

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
@saimaheshtaduri, using Netlify's Deploy Preview I can't see the button working.

**Comment by saimaheshtaduri** [comment]
yes, I didn't display the data. I thought displaying data is a part of another issue, so I just added the functionality of storing the data in local storage. You can see the updates in the application local storage in the inspect page.

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc  show I code the displaying tasks too as another issue ?

**Comment by SauveJeanLuc** [comment]
I've tested it, It's working well behind the scenes.
One thing you have to work on is validation. 
i.e: not accepting an empty string for title and status.

Also, The Buttons Add Task and Cancel should be responsive on click and hover events, so the end-user can know the button was clicked. And you can raise a separate issue for this and I'll assign it to you.

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc  done. I added validation. 
Now if the status or title is empty, I put a basic alert. 
anything else ? please let me know. 
Thanks :)

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc  I have raised another issue for the buttons, please assign it to me. I would gladly work on it. 
Thanks :)

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc done. I added validation. Now if the status or title is empty, I put a basic alert. anything else ? please let me know. Thanks :)

You can limit the status options to complete and incomplete only

**Comment by SauveJeanLuc** [comment]
Also, remember to link this PR to its issue so that once merged, the issue will be closed as well.

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc limited the status options.

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc  review it now :)

**Comment by SauveJeanLuc** [comment]
LGTM

**Comment by SauveJeanLuc** [comment]
LGTM

**Pull request merged**
