### PR TITLE
cursor pointer added to select button

### PR DESCRIPTION
**Pull request by sisirdhakal**
## Description

I added the cursor pointer to the select button in the nav component

## Related Issue

=> The cursor was just normal with no changes on hovering the button.
      So adding the pointer event will increase the user experience.

## Motivation and Context

=> A selecter button mostly has a cursor pointer effect on it. So adding the cursor pointer effect would be appropriate.

## How Has This Been Tested?

=> I installed the npm package and run the project in localhost. I tested the project according to black box test. And found
    there is no cursor event in the select component. 
    My changes made the cursor event on select button to pointer.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
Add screenshots to showcase your changes

**Comment by sisirdhakal** [comment]
photo_6204231489621701103_y
![176d68eb-2774-46bc-888f-a28b5a24b366
](https://user-images.githubusercontent.com/62702558/194767775-0dd22b36-db3f-432c-833b-dc27d4ef7922.jpg)file:///home/saurav/Pictures/photo_6204231489621701102_y.jpg

**Comment by sisirdhakal** [comment]
file:///home/saurav/Pictures/photo_6204231489621701102_y.jpg

**Comment by sisirdhakal** [comment]
photo_6204231489621701102_y

**Comment by sisirdhakal** [comment]
I have added the photo because screenshot doesnot show the cursor effect

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
