### PR TITLE
UX changes done

### PR DESCRIPTION
**Pull request by suryansh-bhatnagar**
## Description

Just changes some design ,alignment and color  of components
## Related Issue
#54 

## Motivation and Context
To enhance user exp.

## How Has This Been Tested?
I compare UI with the provided UI image 

# Checklist:

 My code follows the style guidelines of this project

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots (if appropriate):
- [ 
Screenshot (419)
Screenshot (420)
] ]

### CODE REVIEW

**Comment by SauveJeanLuc** [comment]
You can ommit the plus icon for now.
image

It's not yet accepted.

**Comment by SauveJeanLuc** [comment]
What you will have to change in this PR, is only the words.
It's better of no design-related changes happen here.

**Comment by suryansh-bhatnagar** [comment]
> What you will have to change in this PR, is only the words. It's better of no design-related changes happen here.

ok

**Comment by SauveJeanLuc** [comment]
Resolve conflicts

**Comment by SauveJeanLuc** [comment]
You only have to make changes with words.

image

**Comment by suryansh-bhatnagar** [comment]
> You only have to make changes with words.
> 
> image

@SauveJeanLuc  done

**Comment by SauveJeanLuc** [comment]
@all-contributors add @suryansh-bhatnagar for code

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
